### ISSUE TITLE
Unable to write files

### ISSUE THREAD

**Issue by anilseth** [mfouesneau/ezpadova#10]
Thanks for this awesome tool.  I'm getting an error when it is trying to write the table to a fits file (indented are the input commands)
astropy 4.0.1.post1
python 3.7.6
>>> r = parsec.get_one_isochrone(1e10, 0.003, model='parsec12s', phot='acs_hrc')

Interrogating http://stev.oapd.inaf.it...
Downloading data...http://stev.oapd.inaf.it/tmp/output585733563945.dat

>>> r.write('padova12s_10Gyr_0.7.fits')

Traceback (most recent call last):

  File "<ipython-input-15-3782c6e7f5c3>", line 1, in <module>
    r.write('padova12s_10Gyr_0.7.fits')

  File "/Users/seth/anaconda/envs/py37/lib/python3.7/site-packages/ezpadova/simpletable.py", line 1689, in write
    hdr = _fits_generate_header(self)

  File "/Users/seth/anaconda/envs/py37/lib/python3.7/site-packages/ezpadova/simpletable.py", line 279, in _fits_generate_header
    hdr.update(k, v)

  File "/Users/seth/anaconda/envs/py37/lib/python3.7/site-packages/astropy/io/fits/header.py", line 1153, in update
    'a keyword, value, and comment string.'.format(idx))

ValueError: Header update sequence item #0 is invalid; the item must either be a 2-tuple containing a keyword and value, or a 3-tuple containing a keyword, value, and comment string.

**Comment by mfouesneau** [comment]
Could you download manually the file and check that there is content? From the error message, I suspect the file is empty or something is wrong.

(I cannot check the file is temporary on the server)

**Comment by anilseth** [comment]
No its not blank, I’m able to plot the isochrone and the table definitely has many columns (see output below).   I’m actually able to use this just fine (thanks!), but have to keep querying parsec over and over again as I run my code many times.  

> r = parsec.get_one_isochrone(5e9, 0.008, model='parsec12s', phot='acs_hrc')
> Interrogating http://stev.oapd.inaf.it...
> Downloading data...http://stev.oapd.inaf.it/tmp/output870120245804.dat
> 
> np.shape(r)
> Out[67]: (223,)
> 
> r.colnames
> Out[68]: 
> ('index',
>  'Z',
>  'log(age/yr)',
>  'M_ini',
>  'M_act',
>  'logL/Lo',
>  'logTe',
>  'logG',
>  'mbol',
>  'F220W',
>  'F250W',
>  'F330W',
>  'F344N',
>  'F435W',
>  'F475W',
>  'F550M',
>  'F555W',
>  'F606W',
>  'F625W',
>  'F658N',
>  'F660N',
>  'F775W',
>  'F814W',
>  'F850LP',
>  'F892N',
>  'int_IMF',
>  'stage')

**Comment by mfouesneau** [comment]
I see. The fits format writing is broken. Can you save the file in csv? I'll have a look

**Comment by anilseth** [comment]
Looks like CSV outputting is also broken.  Also, I’ve tried making it into an astropy Table, and that doesn’t work either.
--
r.write('test.csv')
Traceback (most recent call last):

  File "<ipython-input-69-b21516446f75>", line 1, in <module>
    r.write('test.csv')

  File "/Users/seth/anaconda/envs/py37/lib/python3.7/site-packages/ezpadova/simpletable.py", line 1673, in write
    commentedHeader=commentedHeader)

  File "/Users/seth/anaconda/envs/py37/lib/python3.7/site-packages/ezpadova/simpletable.py", line 750, in _ascii_generate_header
    for vk in v.split('\n'):

AttributeError: 'int' object has no attribute 'split'

**Comment by mfouesneau** [comment]
I just pushed an update on simpletable.py which should correct both the csv and fits export issues. @anilseth  Can you test and confirm?

**Comment by anilseth** [comment]
Yes, thanks that fixed it.  However, I'm now getting some warning errors associated with outputting the fits header (the csv runs without error).  Its very long, but comes from having >8 characters in the header.  As I said though, it works just fine, and I can read it back in using astropy Table.read() successfully.
WARNING: VerifyWarning: Keyword name 'cmd_version' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]
WARNING: VerifyWarning: Keyword name 'dust_sourceC' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]

**Comment by mfouesneau** [comment]
FITS is old :) and astropy tries to tell you the HIERARCH card will be used for the header, which should be the default now. I don't know how to remove these sorry. 

Closing the issue. Keep an eye for when the new website is integrated.
