### ISSUE TITLE
Unable to download more than five rows 

### ISSUE THREAD

**Issue by ritviksainarayan** [mfouesneau/ezpadova#13]
For some reason, all isochrone settings are only returning five rows irrespective of whether I use `get_one_isochrone` or `get_t_isochrones` or `get_z_isochrones`. How can I fix this?

**Comment by mfouesneau** [comment]
This should be fixed on the v2.0 branch. Before merging into the main branch, I still need to test a few things. You can try it if you feel adventurous. 
v2.0 works with cmd_3.8 (latest), which means you can get their latest updates, including many isochrones ranging in both ages and metallicity, in one shot.
